<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Cadastro de Professor</title>
</head>
<body>
    <a href="<?=PATH_ROOT?>professor">Voltar</a>
    <hr>
    <form action="<?=PATH_ROOT?>professor/cadastrar" method="post">
        Matrícula:
        <input type="text" name="matricula"><br><br>
        Nome:
        <input type="text" name="nome"><br><br>
        Turmas:<br>
        <select name="turmas[]" multiple="multiple">
            <?=$this->optionsTurma?>
        </select>
        <br><br>
        <input type="submit" value="Cadastrar">
    </form>
</body>
</html>