<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Edição de Professor</title>
</head>
<body>
    <a href="/projeto-tcc/professor">Voltar</a>
    <hr>
    <form action="/controller/editar" method="post">
        <input type="hidden" name="id" value="<?=$this->professor->getId()?>"><br>
        Matrícula:
        <input type="text" name="matricula" value="<?=$this->professor->getMatricula()?>"><br>
        Nome:
        <input type="text" name="nome" value="<?=$this->professor->getNome()?>"><br>
        Turmas:<br>
        <select name="turmas[]" multiple="multiple">
            <?=$this->optionsTurma?>
        </select>
        <br><br>
        <input type="submit" value="Editar">
    </form>
</body>
</html>