<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Cadastro de Professores</title>
</head>
<body>
    <h1>Cadastro de Professores</h1>
    <a href="<?=PATH_ROOT?>">Voltar Index</a>
    ###
    <a href="<?=PATH_ROOT?>professor/cadastrar">Cadastro de Professor</a>
    <hr>
    <table>
        <thead>
        <tr>
            <th>Nome</th>
            <th>Ações</th>
            <th>Turmas</th>
        </tr>
        </thead>
        <tbody>
            <?php foreach($this->professores as $professor): ?>
                <tr>
                    <td><?=$professor->getNome()?></td>
                    <td>
                        <a title="Editar ID: <?=$professor->getId()?>" href="<?=PATH_ROOT?>professor/editar/id/<?=$professor->getId()?>">Editar</a>
                         | 
                        <a title="Excluir ID: <?=$professor->getId()?>" href="<?=PATH_ROOT?>professor/excluir/id/<?=$professor->getId()?>">Excluir</a>
                    </td>
                    <td>
                        <form action="<?=PATH_ROOT?>professor/excluirTurma" method="post">
                            <select name="turmaId">
                                <?php if ($professor->getTurmas()->count() > 0) foreach ($professor->getTurmas() as $turma) : ?>
                                        <option value="<?=$turma->getId()?>"><?=$turma->getNome()?></option>
                                <?php endforeach; ?>
                            </select>
                            <input type="hidden" name="professorId" value="<?=$professor->getId()?>">
                            <input type="submit" value="Excluir Turma">
                        </form>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</body>
</html>