<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Cadastro de Aluno</title>
</head>
<body>
    <a href="<?=PATH_ROOT?>aluno">Voltar</a>
    <hr>
    <form action="<?=PATH_ROOT?>aluno/cadastrar" method="post">
        Matrícula: 
        <input type="text" name="matricula"><br><br>
        Nome: 
        <input type="text" name="nome"><br><br>
        Data de Nascimento: 
        <input type="text" name="data_de_nascimento"><br><br>
        Turma:
        <select name="turma">
            <?=$this->optionsTurma?>
        </select>
        <br><br>
        <input type="submit" value="Cadastrar">
    </form>
</body>
</html>