<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Edição de turma</title>
</head>
<body>
<form action="<?=PATH_ROOT?>turma/editar" method="post">
    <a href="<?=PATH_ROOT?>turma">Voltar</a>
    <hr>
    <input type="hidden" name="id" value="<?=$this->turma->getId()?>"><br>
    Nome: <input type="text" name="nome" value="<?=$this->turma->getNome()?>">
    <br><br>
    <input type="submit" value="Editar">
</form>
</body>
</html>